name: Remove previous app versions
author: reviewable
description: |-
  Remove all versions of the app beyond the set limit.

inputs:
  project_id:
    description: The GCP project ID. Overrides project ID set by credentials.
    required: false

  limit:
    description: A number to set the total allowed deployed versions of your app.
    required: true

  days_to_keep:
    description: |-
      Versions newer than this number of days before today will not be deleted.
      Older versions will be subject to the limit value.
    required: false

  credentials:
    description: |-
      Service account key to use for authentication. This should be the JSON
      formatted private key which can be exported from the Cloud Console. The
      value can be raw or base64-encoded.
    required: false

  service_name:
    description: |-
      The name of the service you want to target with the action.
    required: false

output:
  versions_deleted:
    description: Version numbers that were deleted.

  total_deleted:
    description: Number of versions deleted.

runs:
  using: node12
  main: dist/index.js