name: Check build
on:
  - push
  - pull_request
jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ github.token }}
          submodules: 'true'
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Check for build changes
        run: git diff --quiet
