name: Build appengine-remove
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Commit & Push changes
        uses: EndBug/add-and-commit@v7
        with:
          add: 'build'
          branch: 'master'
          message: 'actions commit: Build ${{ github.run_number }}'

